version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
      MONGO_INITDB_DATABASE: dev
    ports:
      - '27017:27017'
